### PR TITLE
Add support for Keycloak

### PR DESCRIPTION
**Pull request by shanesoh**
Resolves https://github.com/NationalSecurityAgency/skills-service/issues/463

### CODE REVIEW

**Comment by rmmayo** [comment]
Added comment to the ticket: https://github.com/NationalSecurityAgency/skills-service/issues/463#issuecomment-810540110

**Review by rmmayo — CHANGES_REQUESTED** [review]
hi @shanesoh - could you please just add a simple test to the `skills.auth.OAuth2UserConverterServiceSpec` testing the `KeycloakUserConverter`?

**Comment by shanesoh** [comment]
@rmmayo Just did. Please take a look. Thanks!

**Review by rmmayo — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
