### PR TITLE
Security Vulnerability Fixes

### PR DESCRIPTION
**Pull request by TheFoxAtWork**

### CODE REVIEW

**Comment by mosefer** [comment]
@TheFoxAtWork could you pull the latest changes into your fork? I've updated the license check to allow BSD 3 Clause licenses which should permit the CI actions for your PR to succeed. Thanks!

**Comment by TheFoxAtWork** [comment]
> @TheFoxAtWork could you pull the latest changes into your fork? I've updated the license check to allow BSD 3 Clause licenses which should permit the CI actions for your PR to succeed. Thanks!

done.  running....

**Comment by mosefer** [comment]
@TheFoxAtWork I suspect we may have to play a bit of license whack-a-mole, I just added Unlicense to the allow list as the most recent CI actions failed on that.

**Comment by TheFoxAtWork** [comment]
> @TheFoxAtWork I suspect we may have to play a bit of license whack-a-mole, I just added Unlicense to the allow list as the most recent CI actions failed on that.

I'm going to close the PR and submit a new one.  one of the commits is not what i want to include on further research.  standby.

**Pull request closed without merging**
