### PR TITLE
enhancement: use optional chaining, add semicolons and remove unneeded comments

### PR DESCRIPTION
**Pull request by evenstensberg**
Hay! Hope you are having a good, day night or whatever. I removed some unneeded comments that weren't used and added semicolons to missing places. Also added a small syntax sugar, thanks for reviewing, loves <3

### CODE REVIEW

**Comment by evenstensberg** [comment]
Also, this is extremely well written, nice job to everyone!

**Comment by mosefer** [comment]
Thanks! It looks like there are a few eslint errors that are preventing the build from running, can you take a look at:

```
 dashboard/src/components/header/Breadcrumb.vue
  142:1  error  More than 1 blank line not allowed  no-multiple-empty-lines

  dashboard/src/components/projects/MyProjects.vue
  172:15  error  Trailing spaces not allowed  no-trailing-spaces

  dashboard/src/interceptors/clientVersionInterceptor.js
  21:5  error  Expected space(s) after "if"  keyword-spacing
```
Thanks for the contribution!

**Comment by evenstensberg** [comment]
How can I verify? Thx, I think I fixed them now, please check again!

**Review by mosefer — APPROVED** [review]

**Comment by mosefer** [comment]
Looks good!

**Pull request merged**
