### PR TITLE
Ticket#7/forgot password

### PR DESCRIPTION
**Pull request by mosefer**

### CODE REVIEW

**Comment by sudo-may** [comment]
@mosefer Code Review: 
- when resetting redirect to a confirmation page with a larger text; 
  - confirmation page should display should email, something like "We emailed password reset instructions to your@email.org"
  - have a button that takes you to the login page
  - redirect you to the login after the existing timeout
- similar behavior after the password was reset
- add cypress test to validate UI handling of once the token/url is used it's not valid anymore
- allow users to configure timeout without specifing PT prefix
- ``db.changelog-master.xml`` - changeset 2 has not be released yet - roll changeset 3 into 2
- consider enhancing ``DataMigrationDBIT.groovy`` to test creation of  password_reset_token table
- on system settings please add help icon with a quick explanation when this url will get used and why user had to specify it
- implement cypress tests for the system and email configuration tests
- add backend integration tests for email and system settings

**Comment by sudo-may** [comment]
@mosefer thanks for taking care of all the items, few items were forgotten:
- on the password reset page - do not go to the error page if a user enters a non-existent email; display the same message is when the token is not correct; will need a cypress test for that as well
- do not error if the email and system settings are not configured; redirect to the page that explains that this feature is not yet enabled and encourage to reach out to the SkillTree admin
- display/set default value in the Settings > System > 'Password Token Expiration' input field
- decrease redirect timeout period; try 10 seconds if it feels too short please try 15 seconds
- got the following vee-validate error while running cypress tests with the console:
```
VM10710 vee-validate.esm.js:317 Uncaught (in promise) Error: [vee-validate] Validating a non-existent field: "#3". Use "attach()" first.
    at createError (VM2292 vee-validate.esm.js:317)
    at Validator._handleFieldNotFound (VM2292 vee-validate.esm.js:3695)
    at Validator.validate (VM2292 vee-validate.esm.js:3274)
    at ScopedValidator.validate (VM2292 vee-validate.esm.js:2747)
    at fn (VM2292 vee-validate.esm.js:2393)
    at later (VM2292 vee-validate.esm.js:230)
```

**Comment by mosefer** [comment]
@sudo-may addressed requested enhancements, please take a look at ```FeatureService.isPasswordResetFeatureEnabled```, after adding the email sender test, I'm concerned that may be too slow to do every time a user requests a password reset?  It also strikes me that someone could maliciously hammer that endpoint and cause stability issues with the underlying mail server. Thoughts?

**Comment by sudo-may** [comment]
@mosefer 
- please change ``/isFeatureSupported`` endpoint to ``/public/isFeatureSupported``

**Pull request merged**
